#ifndef ACSL_SYNTAX_EXTENSION_H
#define ACSL_SYNTAX_EXTENSION_H 1

#define ASTRAVER_TOOLCHAIN 1

#ifdef ASTRAVER_TOOLCHAIN /* used by default */
# define FRAMAC_ISSPACE_BUG || c == '\v'
# define ACSL_EXT_NO_OVERFLOW %
# define ACSL_EXT_NO_OVERFLOW_CMNT /*@%*/
#else
# define FRAMAC_ISSPACE_BUG
# define ACSL_EXT_NO_OVERFLOW
# define ACSL_EXT_NO_OVERFLOW_CMNT
#endif

#endif /* ACSL_SYNTAX_EXTENSION_H */
