(* This file is generated by Why3's Coq driver *)
(* Beware! Only edit allowed sections below    *)
Require Import BuiltIn.
Require Enum_intf.
Require Enum.
Require Int8.
Require Int32.
Require Uint64.
Require Jessie_pointer.
Require Jessie_alloc_table.
Require Jessie_memory.
Require Jessie_pset.
Require Jessie_pset_range.
Require Jessie_assigns.
Require Jessie_tag_id.
Require Jessie_tag.
Require Jessie_tag_table_type.
Require Jessie_voidp.
Require Jessie_voidp_tag_id.
Require Jessie_tag_table.
Require Jessie_charp_tag_id.
Require Jessie_allocable.

(* Why3 assumption *)
Definition unit := unit.

Axiom Abs_le : forall (x:Z) (y:Z), ((ZArith.BinInt.Z.abs x) <= y)%Z <->
  (((-y)%Z <= x)%Z /\ (x <= y)%Z).

Axiom Div_mult_simplest : forall (x:Z) (y:Z), ((x >= 0%Z)%Z /\
  (0%Z < y)%Z) -> ((ZArith.BinInt.Z.quot (x * y)%Z y) = x).

(* Why3 assumption *)
Inductive ref (a:Type) :=
  | mk_ref : a -> ref a.
Axiom ref_WhyType : forall (a:Type) {a_WT:WhyType a}, WhyType (ref a).
Existing Instance ref_WhyType.
Implicit Arguments mk_ref [[a]].

(* Why3 assumption *)
Definition contents {a:Type} {a_WT:WhyType a} (v:(ref a)): a :=
  match v with
  | (mk_ref x) => x
  end.

Axiom map : forall (a:Type) (b:Type), Type.
Parameter map_WhyType : forall (a:Type) {a_WT:WhyType a}
  (b:Type) {b_WT:WhyType b}, WhyType (map a b).
Existing Instance map_WhyType.

Parameter get: forall {a:Type} {a_WT:WhyType a} {b:Type} {b_WT:WhyType b},
  (map a b) -> a -> b.

Parameter set: forall {a:Type} {a_WT:WhyType a} {b:Type} {b_WT:WhyType b},
  (map a b) -> a -> b -> (map a b).

Axiom Select_eq : forall {a:Type} {a_WT:WhyType a} {b:Type} {b_WT:WhyType b},
  forall (m:(map a b)), forall (a1:a) (a2:a), forall (b1:b), (a1 = a2) ->
  ((get (set m a1 b1) a2) = b1).

Axiom Select_neq : forall {a:Type} {a_WT:WhyType a}
  {b:Type} {b_WT:WhyType b}, forall (m:(map a b)), forall (a1:a) (a2:a),
  forall (b1:b), (~ (a1 = a2)) -> ((get (set m a1 b1) a2) = (get m a2)).

(* Why3 assumption *)
Definition valid_str (s:(Jessie_pointer.pointer Jessie_voidp.voidP))
  (voidP_s_2_alloc_table_at_L:(Jessie_alloc_table.alloc_table
  Jessie_voidp.voidP)) (charP_charM_s_2_at_L:(map (Jessie_pointer.pointer
  Jessie_voidp.voidP) Int8.t)): Prop := exists n_1:Uint64.t,
  ((get charP_charM_s_2_at_L (Jessie_pointer.shift s
  (Uint64.to_int n_1))) = (Int8.of_int 0%Z)) /\
  ((0%Z <= (Uint64.to_int n_1))%Z ->
  (((Jessie_alloc_table.offset_min voidP_s_2_alloc_table_at_L s) <= 0%Z)%Z /\
  ((Jessie_alloc_table.offset_max voidP_s_2_alloc_table_at_L
  s) >= (Uint64.to_int n_1))%Z)).

Axiom Valid_str_shift1 : forall (voidP_s_0_8_alloc_table_at_L:(Jessie_alloc_table.alloc_table
  Jessie_voidp.voidP)), forall (charP_charM_s_0_8_at_L:(map
  (Jessie_pointer.pointer Jessie_voidp.voidP) Int8.t)),
  forall (s_0_0:(Jessie_pointer.pointer Jessie_voidp.voidP)),
  ((~ ((get charP_charM_s_0_8_at_L s_0_0) = (Int8.of_int 0%Z))) /\ (valid_str
  s_0_0 voidP_s_0_8_alloc_table_at_L charP_charM_s_0_8_at_L)) -> (valid_str
  (Jessie_pointer.shift s_0_0 1%Z) voidP_s_0_8_alloc_table_at_L
  charP_charM_s_0_8_at_L).

Axiom Valid_str_strend : forall (voidP_s_1_9_alloc_table_at_L:(Jessie_alloc_table.alloc_table
  Jessie_voidp.voidP)), forall (charP_charM_s_1_9_at_L:(map
  (Jessie_pointer.pointer Jessie_voidp.voidP) Int8.t)),
  forall (s_1:(Jessie_pointer.pointer Jessie_voidp.voidP)),
  ((((Jessie_alloc_table.offset_min voidP_s_1_9_alloc_table_at_L
  s_1) <= 0%Z)%Z /\
  ((Jessie_alloc_table.offset_max voidP_s_1_9_alloc_table_at_L
  s_1) >= 0%Z)%Z) /\ ((get charP_charM_s_1_9_at_L
  s_1) = (Int8.of_int 0%Z))) -> (valid_str s_1 voidP_s_1_9_alloc_table_at_L
  charP_charM_s_1_9_at_L).

Parameter strlen: (Jessie_pointer.pointer Jessie_voidp.voidP) -> (map
  (Jessie_pointer.pointer Jessie_voidp.voidP) Int8.t) -> Uint64.t.

Axiom Strlen_before_null : forall (voidP_s_3_10_alloc_table_at_L:(Jessie_alloc_table.alloc_table
  Jessie_voidp.voidP)), forall (charP_charM_s_3_10_at_L:(map
  (Jessie_pointer.pointer Jessie_voidp.voidP) Int8.t)),
  forall (s_3:(Jessie_pointer.pointer Jessie_voidp.voidP)), forall (i_1:Z),
  ((valid_str s_3 voidP_s_3_10_alloc_table_at_L charP_charM_s_3_10_at_L) /\
  ((0%Z <= i_1)%Z /\ (i_1 < (Uint64.to_int (strlen s_3
  charP_charM_s_3_10_at_L)))%Z)) -> ~ ((get charP_charM_s_3_10_at_L
  (Jessie_pointer.shift s_3 i_1)) = (Int8.of_int 0%Z)).

Axiom Strlen_at_null : forall (voidP_s_4_11_alloc_table_at_L:(Jessie_alloc_table.alloc_table
  Jessie_voidp.voidP)), forall (charP_charM_s_4_11_at_L:(map
  (Jessie_pointer.pointer Jessie_voidp.voidP) Int8.t)),
  forall (s_4:(Jessie_pointer.pointer Jessie_voidp.voidP)), (valid_str s_4
  voidP_s_4_11_alloc_table_at_L charP_charM_s_4_11_at_L) ->
  ((get charP_charM_s_4_11_at_L (Jessie_pointer.shift s_4
  (Uint64.to_int (strlen s_4
  charP_charM_s_4_11_at_L)))) = (Int8.of_int 0%Z)).

Axiom Strlen_shift : forall (voidP_s_5_12_alloc_table_at_L:(Jessie_alloc_table.alloc_table
  Jessie_voidp.voidP)), forall (charP_charM_s_5_12_at_L:(map
  (Jessie_pointer.pointer Jessie_voidp.voidP) Int8.t)),
  forall (s_5:(Jessie_pointer.pointer Jessie_voidp.voidP)),
  forall (i_2:Uint64.t), ((valid_str s_5 voidP_s_5_12_alloc_table_at_L
  charP_charM_s_5_12_at_L) /\ (Uint64.infix_lseq i_2 (strlen s_5
  charP_charM_s_5_12_at_L))) ->
  ((Uint64.to_int (strlen (Jessie_pointer.shift s_5 (Uint64.to_int i_2))
  charP_charM_s_5_12_at_L)) = ((Uint64.to_int (strlen s_5
  charP_charM_s_5_12_at_L)) - (Uint64.to_int i_2))%Z).

Axiom Strlen_shift_ex : forall (voidP_s_6_13_alloc_table_at_L:(Jessie_alloc_table.alloc_table
  Jessie_voidp.voidP)), forall (charP_charM_s_6_13_at_L:(map
  (Jessie_pointer.pointer Jessie_voidp.voidP) Int8.t)),
  forall (s_6:(Jessie_pointer.pointer Jessie_voidp.voidP)),
  forall (i_3:Uint64.t), ((valid_str s_6 voidP_s_6_13_alloc_table_at_L
  charP_charM_s_6_13_at_L) /\ ((Uint64.infix_ls (Uint64.of_int 0%Z) i_3) /\
  (Uint64.infix_lseq i_3 (strlen s_6 charP_charM_s_6_13_at_L)))) ->
  (Uint64.infix_ls (strlen (Jessie_pointer.shift s_6 (Uint64.to_int i_3))
  charP_charM_s_6_13_at_L) (strlen s_6 charP_charM_s_6_13_at_L)).

Axiom Strlen_shift1 : forall (voidP_s_7_14_alloc_table_at_L:(Jessie_alloc_table.alloc_table
  Jessie_voidp.voidP)), forall (charP_charM_s_7_14_at_L:(map
  (Jessie_pointer.pointer Jessie_voidp.voidP) Int8.t)),
  forall (s_7:(Jessie_pointer.pointer Jessie_voidp.voidP)), ((valid_str s_7
  voidP_s_7_14_alloc_table_at_L charP_charM_s_7_14_at_L) /\
  ~ ((get charP_charM_s_7_14_at_L s_7) = (Int8.of_int 0%Z))) ->
  ((Uint64.to_int (strlen s_7
  charP_charM_s_7_14_at_L)) = (1%Z + (Uint64.to_int (strlen (Jessie_pointer.shift s_7
  1%Z) charP_charM_s_7_14_at_L)))%Z).

Axiom Strlen_pointers : forall (voidP_s_8_15_alloc_table_at_L:(Jessie_alloc_table.alloc_table
  Jessie_voidp.voidP)), forall (charP_charM_s_8_15_at_L:(map
  (Jessie_pointer.pointer Jessie_voidp.voidP) Int8.t)),
  forall (s_8:(Jessie_pointer.pointer Jessie_voidp.voidP)),
  forall (sc:(Jessie_pointer.pointer Jessie_voidp.voidP)), ((valid_str s_8
  voidP_s_8_15_alloc_table_at_L charP_charM_s_8_15_at_L) /\ ((valid_str sc
  voidP_s_8_15_alloc_table_at_L charP_charM_s_8_15_at_L) /\
  ((Jessie_pointer.same_block s_8 sc) /\ ((Jessie_pointer.same_block s_8
  sc) /\ (((Jessie_pointer.sub_pointer s_8 sc) <= 0%Z)%Z /\ forall (i_4:Z),
  ((0%Z <= i_4)%Z /\ (i_4 <= (Jessie_pointer.sub_pointer sc s_8))%Z) ->
  ~ ((get charP_charM_s_8_15_at_L (Jessie_pointer.shift s_8
  i_4)) = (Int8.of_int 0%Z))))))) -> (Uint64.infix_lseq (strlen sc
  charP_charM_s_8_15_at_L) (strlen s_8 charP_charM_s_8_15_at_L)).

Axiom Strlen_main : forall (voidP_s_9_17_alloc_table_at_L:(Jessie_alloc_table.alloc_table
  Jessie_voidp.voidP)), forall (charP_charM_s_9_17_at_L:(map
  (Jessie_pointer.pointer Jessie_voidp.voidP) Int8.t)),
  forall (s_9:(Jessie_pointer.pointer Jessie_voidp.voidP)),
  forall (n_2:Uint64.t), ((valid_str s_9 voidP_s_9_17_alloc_table_at_L
  charP_charM_s_9_17_at_L) /\ (((get charP_charM_s_9_17_at_L
  (Jessie_pointer.shift s_9 (Uint64.to_int n_2))) = (Int8.of_int 0%Z)) /\
  forall (i_5:Z), ((0%Z <= i_5)%Z /\ (i_5 < (Uint64.to_int n_2))%Z) ->
  ~ ((get charP_charM_s_9_17_at_L (Jessie_pointer.shift s_9
  i_5)) = (Int8.of_int 0%Z)))) -> ((strlen s_9
  charP_charM_s_9_17_at_L) = n_2).

Axiom Valid_str_shiftn : forall (voidP_s_10_18_alloc_table_at_L:(Jessie_alloc_table.alloc_table
  Jessie_voidp.voidP)), forall (charP_charM_s_10_18_at_L:(map
  (Jessie_pointer.pointer Jessie_voidp.voidP) Int8.t)),
  forall (s_10:(Jessie_pointer.pointer Jessie_voidp.voidP)), forall (i_6:Z),
  ((valid_str s_10 voidP_s_10_18_alloc_table_at_L
  charP_charM_s_10_18_at_L) /\ ((0%Z <= i_6)%Z /\
  (i_6 < (Uint64.to_int (strlen s_10 charP_charM_s_10_18_at_L)))%Z)) ->
  (valid_str (Jessie_pointer.shift s_10 i_6) voidP_s_10_18_alloc_table_at_L
  charP_charM_s_10_18_at_L).

Axiom Strlen_definition : forall (s_2:(Jessie_pointer.pointer
  Jessie_voidp.voidP)), forall (charP_charM_s_2_3_at_L:(map
  (Jessie_pointer.pointer Jessie_voidp.voidP) Int8.t)),
  (((get charP_charM_s_2_3_at_L (Jessie_pointer.shift s_2
  0%Z)) = (Int8.of_int 0%Z)) -> ((strlen s_2
  charP_charM_s_2_3_at_L) = (Uint64.of_int 0%Z))) /\
  ((~ ((get charP_charM_s_2_3_at_L (Jessie_pointer.shift s_2
  0%Z)) = (Int8.of_int 0%Z))) -> ((strlen s_2
  charP_charM_s_2_3_at_L) = (Uint64.of_int (1%Z + (Uint64.to_int (strlen (Jessie_pointer.shift s_2
  1%Z) charP_charM_s_2_3_at_L)))%Z))).

(* Why3 goal *)
Theorem WP_parameter_strcat_ensures_default : forall (dest_9:(Jessie_pointer.pointer
  Jessie_voidp.voidP)) (src_5:(Jessie_pointer.pointer Jessie_voidp.voidP))
  (charP_charM_dest_9_5:(map (Jessie_pointer.pointer Jessie_voidp.voidP)
  Int8.t)) (voidP_dest_9_5_alloc_table:(Jessie_alloc_table.alloc_table
  Jessie_voidp.voidP))
  (voidP_src_5_6_alloc_table:(Jessie_alloc_table.alloc_table
  Jessie_voidp.voidP)) (voidP_src_5_6_tag_table:(map (Jessie_pointer.pointer
  Jessie_voidp.voidP) (Jessie_tag_id.tag_id Jessie_voidp.voidP)))
  (voidP_dest_9_5_tag_table:(map (Jessie_pointer.pointer Jessie_voidp.voidP)
  (Jessie_tag_id.tag_id Jessie_voidp.voidP))) (charP_charM_src_5_6:(map
  (Jessie_pointer.pointer Jessie_voidp.voidP) Int8.t)),
  (((Jessie_allocable.allocated voidP_src_5_6_alloc_table src_5) ->
  (((get voidP_src_5_6_tag_table src_5) = Jessie_charp_tag_id.charP_tag) /\
  forall (i:Z), (((Jessie_alloc_table.offset_min voidP_src_5_6_alloc_table
  src_5) <= i)%Z /\
  (i < (Jessie_alloc_table.offset_max voidP_src_5_6_alloc_table src_5))%Z) ->
  ((get voidP_src_5_6_tag_table (Jessie_pointer.shift src_5
  i)) = Jessie_charp_tag_id.charP_tag))) /\ (((Jessie_allocable.allocated
  voidP_dest_9_5_alloc_table dest_9) -> (((get voidP_dest_9_5_tag_table
  dest_9) = Jessie_charp_tag_id.charP_tag) /\ forall (i:Z),
  (((Jessie_alloc_table.offset_min voidP_dest_9_5_alloc_table
  dest_9) <= i)%Z /\
  (i < (Jessie_alloc_table.offset_max voidP_dest_9_5_alloc_table
  dest_9))%Z) -> ((get voidP_dest_9_5_tag_table (Jessie_pointer.shift dest_9
  i)) = Jessie_charp_tag_id.charP_tag))) /\ ((valid_str src_5
  voidP_src_5_6_alloc_table charP_charM_src_5_6) /\ ((valid_str dest_9
  voidP_dest_9_5_alloc_table charP_charM_dest_9_5) /\
  ((((Uint64.to_int (strlen dest_9
  charP_charM_dest_9_5)) + (Uint64.to_int (strlen src_5
  charP_charM_src_5_6)))%Z <= 100%Z)%Z /\ ((((Uint64.to_int (strlen dest_9
  charP_charM_dest_9_5)) + (Uint64.to_int (strlen src_5
  charP_charM_src_5_6)))%Z = (Uint64.to_int (Uint64.of_int ((Uint64.to_int (strlen dest_9
  charP_charM_dest_9_5)) + (Uint64.to_int (strlen src_5
  charP_charM_src_5_6)))%Z))) /\ ((0%Z <= ((Uint64.to_int (strlen dest_9
  charP_charM_dest_9_5)) + (Uint64.to_int (strlen src_5
  charP_charM_src_5_6)))%Z)%Z ->
  (((Jessie_alloc_table.offset_min voidP_dest_9_5_alloc_table
  dest_9) <= 0%Z)%Z /\
  ((Jessie_alloc_table.offset_max voidP_dest_9_5_alloc_table
  dest_9) >= ((Uint64.to_int (strlen dest_9
  charP_charM_dest_9_5)) + (Uint64.to_int (strlen src_5
  charP_charM_src_5_6)))%Z)%Z)))))))) -> forall (tmp:(Jessie_pointer.pointer
  Jessie_voidp.voidP)), (tmp = dest_9) -> let o := (strlen tmp
  charP_charM_dest_9_5) in ((((get charP_charM_dest_9_5
  (Jessie_pointer.shift tmp (Uint64.to_int o))) = (Int8.of_int 0%Z)) /\
  forall (i_7:Z), ((0%Z <= i_7)%Z /\ (i_7 < (Uint64.to_int o))%Z) ->
  ~ ((get charP_charM_dest_9_5 (Jessie_pointer.shift tmp
  i_7)) = (Int8.of_int 0%Z))) -> forall (dest_len:Uint64.t),
  (dest_len = o) -> forall (mutable_dest_9:(Jessie_pointer.pointer
  Jessie_voidp.voidP)), ((((Jessie_pointer.same_block tmp mutable_dest_9) /\
  (((Jessie_pointer.sub_pointer tmp mutable_dest_9) <= 0%Z)%Z /\
  ((Jessie_pointer.same_block mutable_dest_9 (Jessie_pointer.shift tmp
  (Uint64.to_int dest_len))) /\ ((Jessie_pointer.sub_pointer mutable_dest_9
  (Jessie_pointer.shift tmp (Uint64.to_int dest_len))) <= 0%Z)%Z))) /\
  ((valid_str mutable_dest_9 voidP_dest_9_5_alloc_table
  charP_charM_dest_9_5) /\ forall (i_8:Z), ((0%Z <= i_8)%Z /\
  (i_8 < (Jessie_pointer.sub_pointer mutable_dest_9 tmp))%Z) ->
  ~ ((get charP_charM_dest_9_5 (Jessie_pointer.shift tmp
  i_8)) = (Int8.of_int 0%Z)))) /\ (Jessie_assigns.not_assigns
  voidP_dest_9_5_alloc_table voidP_dest_9_5_alloc_table charP_charM_dest_9_5
  charP_charM_dest_9_5
  (Jessie_pset_range.pset_range (Jessie_pset.pset_singleton dest_9)
  (Uint64.to_int (strlen dest_9 charP_charM_dest_9_5))
  ((Uint64.to_int (strlen dest_9
  charP_charM_dest_9_5)) + (Uint64.to_int (strlen src_5
  charP_charM_src_5_6)))%Z))) -> forall (o1:Int8.t),
  ((Int8.to_int o1) = 0%Z) -> (((get charP_charM_dest_9_5
  mutable_dest_9) = o1) -> (((get charP_charM_dest_9_5
  mutable_dest_9) = (Int8.of_int 0%Z)) ->
  ((mutable_dest_9 = (Jessie_pointer.shift tmp (Uint64.to_int dest_len))) ->
  (((strlen tmp charP_charM_dest_9_5) = dest_len) ->
  forall (osrc:(Jessie_pointer.pointer Jessie_voidp.voidP)),
  (osrc = src_5) -> forall (mdest:(Jessie_pointer.pointer
  Jessie_voidp.voidP)), (mdest = mutable_dest_9) ->
  forall (mutable_src_5:(Jessie_pointer.pointer Jessie_voidp.voidP))
  (mutable_dest_91:(Jessie_pointer.pointer Jessie_voidp.voidP))
  (charP_charM_dest_9_51:(map (Jessie_pointer.pointer Jessie_voidp.voidP)
  Int8.t)), ((((Jessie_pointer.same_block osrc mutable_src_5) /\
  (((Jessie_pointer.sub_pointer osrc mutable_src_5) <= 0%Z)%Z /\
  ((Jessie_pointer.same_block mutable_src_5 (Jessie_pointer.shift osrc
  (Uint64.to_int (strlen osrc charP_charM_src_5_6)))) /\
  ((Jessie_pointer.sub_pointer mutable_src_5 (Jessie_pointer.shift osrc
  (Uint64.to_int (strlen osrc charP_charM_src_5_6)))) <= 0%Z)%Z))) /\
  (((Jessie_pointer.same_block mdest mutable_dest_91) /\
  (((Jessie_pointer.sub_pointer mdest mutable_dest_91) <= 0%Z)%Z /\
  ((Jessie_pointer.same_block mutable_dest_91 (Jessie_pointer.shift mdest
  (Uint64.to_int (strlen osrc charP_charM_src_5_6)))) /\
  ((Jessie_pointer.sub_pointer mutable_dest_91 (Jessie_pointer.shift mdest
  (Uint64.to_int (strlen osrc charP_charM_src_5_6)))) <= 0%Z)%Z))) /\
  (((Jessie_pointer.sub_pointer mutable_src_5
  osrc) = (Jessie_pointer.sub_pointer mutable_dest_91 mdest)) /\ ((valid_str
  mutable_src_5 voidP_src_5_6_alloc_table charP_charM_src_5_6) /\
  ((forall (i_9:Z), ((0%Z <= i_9)%Z /\
  (i_9 < (Jessie_pointer.sub_pointer mutable_src_5 osrc))%Z) ->
  ((get charP_charM_dest_9_51 (Jessie_pointer.shift mdest
  i_9)) = (get charP_charM_src_5_6 (Jessie_pointer.shift osrc i_9)))) /\
  forall (i_10:Z), ((0%Z <= i_10)%Z /\
  (i_10 < (Jessie_pointer.sub_pointer mutable_dest_91 tmp))%Z) ->
  ~ ((get charP_charM_dest_9_51 (Jessie_pointer.shift tmp
  i_10)) = (Int8.of_int 0%Z))))))) /\ ((Jessie_assigns.not_assigns
  voidP_dest_9_5_alloc_table voidP_dest_9_5_alloc_table charP_charM_dest_9_5
  charP_charM_dest_9_51
  (Jessie_pset_range.pset_range (Jessie_pset.pset_singleton mdest) 0%Z
  (Uint64.to_int (strlen osrc charP_charM_src_5_6)))) /\
  (Jessie_assigns.not_assigns voidP_dest_9_5_alloc_table
  voidP_dest_9_5_alloc_table charP_charM_dest_9_5 charP_charM_dest_9_51
  (Jessie_pset_range.pset_range (Jessie_pset.pset_singleton dest_9)
  (Uint64.to_int (strlen dest_9 charP_charM_dest_9_5))
  ((Uint64.to_int (strlen dest_9
  charP_charM_dest_9_5)) + (Uint64.to_int (strlen src_5
  charP_charM_src_5_6)))%Z)))) -> forall (tmp_1:(Jessie_pointer.pointer
  Jessie_voidp.voidP)), (tmp_1 = mutable_dest_91) -> forall (o2:Int32.t),
  ((Int32.to_int o2) = 1%Z) ->
  forall (mutable_dest_92:(Jessie_pointer.pointer Jessie_voidp.voidP)),
  (mutable_dest_92 = (Jessie_pointer.shift mutable_dest_91
  (Int32.to_int o2))) -> forall (tmp_3:(Jessie_pointer.pointer
  Jessie_voidp.voidP)), (tmp_3 = mutable_src_5) -> forall (o3:Int32.t),
  ((Int32.to_int o3) = 1%Z) -> forall (mutable_src_51:(Jessie_pointer.pointer
  Jessie_voidp.voidP)), (mutable_src_51 = (Jessie_pointer.shift mutable_src_5
  (Int32.to_int o3))) -> forall (tmp_2:Int8.t),
  (tmp_2 = (get charP_charM_src_5_6 tmp_3)) ->
  forall (charP_charM_dest_9_52:(map (Jessie_pointer.pointer
  Jessie_voidp.voidP) Int8.t)),
  (charP_charM_dest_9_52 = (set charP_charM_dest_9_51 tmp_1 tmp_2)) ->
  forall (o4:Int32.t), ((Int32.to_int o4) = 0%Z) -> forall (o5:Int32.t),
  ((Int32.to_int o5) = (Int8.to_int tmp_2)) -> ((o5 = o4) ->
  ((forall (i_11:Z), ((0%Z <= i_11)%Z /\
  (i_11 < (Uint64.to_int dest_len))%Z) -> ((get charP_charM_dest_9_5
  (Jessie_pointer.shift dest_9 i_11)) = (get charP_charM_dest_9_52
  (Jessie_pointer.shift tmp i_11)))) -> ((((get charP_charM_dest_9_52
  (Jessie_pointer.shift mutable_dest_92 (-1%Z)%Z)) = (Int8.of_int 0%Z)) /\
  ((get charP_charM_src_5_6 (Jessie_pointer.shift mutable_src_51
  (-1%Z)%Z)) = (Int8.of_int 0%Z))) -> (((Jessie_pointer.shift mutable_dest_92
  (-1%Z)%Z) = (Jessie_pointer.shift (Jessie_pointer.shift tmp
  (Uint64.to_int dest_len)) (Uint64.to_int (strlen osrc
  charP_charM_src_5_6)))) -> (((Uint64.to_int (strlen osrc
  charP_charM_src_5_6)) = ((Jessie_pointer.sub_pointer mutable_src_51
  osrc) - 1%Z)%Z) -> ((exists n_3:Uint64.t, ((get charP_charM_dest_9_52
  (Jessie_pointer.shift tmp (Uint64.to_int n_3))) = (Int8.of_int 0%Z)) /\
  (((0%Z <= (Uint64.to_int n_3))%Z ->
  (((Jessie_alloc_table.offset_min voidP_dest_9_5_alloc_table
  tmp) <= 0%Z)%Z /\
  ((Jessie_alloc_table.offset_max voidP_dest_9_5_alloc_table
  tmp) >= (Uint64.to_int n_3))%Z)) /\
  (n_3 = (Uint64.of_int ((Uint64.to_int dest_len) + (Uint64.to_int (strlen osrc
  charP_charM_src_5_6)))%Z)))) -> ((valid_str tmp voidP_dest_9_5_alloc_table
  charP_charM_dest_9_52) -> (((get charP_charM_dest_9_52
  (Jessie_pointer.shift tmp
  (Uint64.to_int (Uint64.of_int ((Uint64.to_int dest_len) + (Uint64.to_int (strlen osrc
  charP_charM_src_5_6)))%Z)))) = (Int8.of_int 0%Z)) -> ((forall (i_12:Z),
  ((0%Z <= i_12)%Z /\
  (i_12 < (Uint64.to_int (Uint64.of_int ((Uint64.to_int dest_len) + (Uint64.to_int (strlen osrc
  charP_charM_src_5_6)))%Z)))%Z) -> ~ ((get charP_charM_dest_9_52
  (Jessie_pointer.shift tmp i_12)) = (Int8.of_int 0%Z))) -> ((strlen tmp
  charP_charM_dest_9_52) = (Uint64.of_int ((Uint64.to_int dest_len) + (Uint64.to_int (strlen osrc
  charP_charM_src_5_6)))%Z)))))))))))))))).
(* Why3 intros dest_9 src_5 charP_charM_dest_9_5 voidP_dest_9_5_alloc_table
        voidP_src_5_6_alloc_table voidP_src_5_6_tag_table
        voidP_dest_9_5_tag_table charP_charM_src_5_6
        (h1,(h2,(h3,(h4,(h5,(h6,h7)))))) tmp h8 o (h9,h10) dest_len h11
        mutable_dest_9 (((h12,(h13,(h14,h15))),(h16,h17)),h18) o1 h19 h20 h21
        h22 h23 osrc h24 mdest h25 mutable_src_5 mutable_dest_91
        charP_charM_dest_9_51
        (((h26,(h27,(h28,h29))),((h30,(h31,(h32,h33))),(h34,(h35,(h36,h37))))),(h38,h39))
        tmp_1 h40 o2 h41 mutable_dest_92 h42 tmp_3 h43 o3 h44 mutable_src_51
        h45 tmp_2 h46 charP_charM_dest_9_52 h47 o4 h48 o5 h49 h50 h51
        (h52,h53) h54 h55 (n_3,(h56,(h57,h58))) h59 h60 h61. *)
intros dest_9 src_5 charP_charM_dest_9_5 voidP_dest_9_5_alloc_table
voidP_src_5_6_alloc_table voidP_src_5_6_tag_table voidP_dest_9_5_tag_table
charP_charM_src_5_6 (h1,(h2,(h3,(h4,(h5,(h6,h7)))))) tmp h8 o (h9,h10)
dest_len h11 mutable_dest_9 (((h12,(h13,(h14,h15))),(h16,h17)),h18) o1 h19
h20 h21 h22 h23 osrc h24 mdest h25 mutable_src_5 mutable_dest_91
charP_charM_dest_9_51
(((h26,(h27,(h28,h29))),((h30,(h31,(h32,h33))),(h34,(h35,(h36,h37))))),(h38,h39))
tmp_1 h40 o2 h41 mutable_dest_92 h42 tmp_3 h43 o3 h44 mutable_src_51 h45
tmp_2 h46 charP_charM_dest_9_52 h47 o4 h48 o5 h49 h50 h51 (h52,h53) h54 h55
(n_3,(h56,(h57,h58))) h59 h60 h61.

Qed.

